# Use the specified base image
FROM  mcr.microsoft.com/devcontainers/typescript-node

# Install NPM packages in packages.json
# Use the specified base image
FROM  mcr.microsoft.com/devcontainers/typescript-node

# # CLI steps 
# npm init --yes
# npm create astro@latest -- --template blog
# https://github.com/OliverSpeir/remark-imgattr


